import { SearchIcon } from "@/components/ui/Icons";
import { shopFilters } from "@/data/shopFilters";

type Props = { search: string; setSearch: (v:string)=>void; category:string; setCategory:(v:string)=>void; brand:string; setBrand:(v:string)=>void; size:string; setSize:(v:string)=>void; onlyAvailable:boolean; setOnlyAvailable:(v:boolean)=>void; maxPrice:number; setMaxPrice:(v:number)=>void; clear:()=>void };
export function ShopFilterSidebar(p: Props) {
  const Group = ({ title, items, value, setValue }: { title:string; items:{label:string;value:string}[]; value:string; setValue:(v:string)=>void }) => <div className="border-t border-borderBlue py-4"><h3 className="mb-3 text-sm font-black">{title}</h3>{items.map(item => <label className="mb-2.5 flex cursor-pointer items-center gap-2 text-[11px] font-bold" key={item.value}><input className="accent-navy" type="checkbox" checked={value === item.value} onChange={() => setValue(value === item.value ? "" : item.value)} />{item.label}</label>)}</div>;
  return <aside className="h-fit rounded-xl border border-borderBlue bg-white p-4 shadow-card lg:sticky lg:top-3">
    <h2 className="text-center text-sm font-black">جستجوی محصول</h2><div className="relative mt-3"><input value={p.search} onChange={e=>p.setSearch(e.target.value)} placeholder="جستجو در محصولات ..." className="h-10 w-full rounded-full border border-borderBlue bg-[#f7f9fd] pr-4 pl-10 text-[11px] outline-none focus:border-navy" /><SearchIcon className="absolute left-3 top-2.5 size-5" /></div>
    <Group title="دسته بندی" items={shopFilters.categories} value={p.category} setValue={p.setCategory}/><Group title="برند" items={shopFilters.brands} value={p.brand} setValue={p.setBrand}/><Group title="سایز" items={shopFilters.sizes} value={p.size} setValue={p.setSize}/>
    <div className="border-t border-borderBlue py-4"><h3 className="mb-2 text-sm font-black">سقف قیمت</h3><p className="mb-3 rounded-lg bg-softBlue p-2 text-center text-xs font-black text-royal">{new Intl.NumberFormat("fa-IR").format(p.maxPrice)} تومان</p><input aria-label="حداکثر قیمت" type="range" min="50000" max="5000000" step="50000" value={p.maxPrice} onChange={e=>p.setMaxPrice(Number(e.target.value))} className="w-full accent-[#f59a00]"/><div className="flex justify-between text-[10px] text-muted"><span>۵۰,۰۰۰</span><span>۵,۰۰۰,۰۰۰</span></div></div>
    <div className="border-t border-borderBlue py-4"><h3 className="mb-3 text-sm font-black">موجودی</h3><label className="flex items-center gap-2 text-[11px] font-bold"><input type="checkbox" checked={p.onlyAvailable} onChange={e=>p.setOnlyAvailable(e.target.checked)} />فقط کالاهای موجود</label></div>
    <div className="rounded-lg bg-emerald-50 px-3 py-2 text-center text-[11px] font-bold text-emerald-700">فیلترها به‌صورت زنده اعمال می‌شوند</div><button onClick={p.clear} className="mt-3 w-full rounded-lg border border-borderBlue py-2 text-[11px] font-bold text-muted transition hover:bg-softBlue" type="button">↻ پاک کردن همه فیلترها</button>
  </aside>;
}
